DROP TABLE IF EXISTS `users`;

CREATE TABLE `users` (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    points INT DEFAULT 0
);

DROP TABLE IF EXISTS brands;
CREATE TABLE brands (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL
);

DROP TABLE IF EXISTS notice;
CREATE TABLE notice (
    id INT PRIMARY KEY AUTO_INCREMENT,
    content TEXT NOT NULL
);

DROP TABLE IF EXISTS brands;
CREATE TABLE brands (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL
);